name: "Update"

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 7 * * *"

jobs:
  update:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "write"

    steps:
      - uses: "actions/checkout@v5"
      - uses: "DeterminateSystems/nix-installer-action@v21"
      - uses: "DeterminateSystems/magic-nix-cache-action@v13"

      - name: "Update flake"
        run: nix flake update

      - name: "Update grammars"
        run: nix develop --command python ./update.py

      - name: "Ensure it builds"
        run: nix build

      - name: "Commit changes"
        uses: "EndBug/add-and-commit@v9"
        with:
          message: "chore: update plugin and grammars"
          default_author: "github_actions"
